version: '3'

services:
  postgresql:
    image: postgres
    container_name: 'liquidation-bot-pg'
    ports:
      - '5400:5432'
    environment:
      - POSTGRES_USER="pg_local"
      - POSTGRES_PASSWORD="dont_cage_the_elephants"
    volumes:
      - liquidation_bot_pg_data:/var/lib/postgresql/data
    restart: always

  # redis:
  #   image: 'redis:latest'
  #   container_name: liquidation-bot-redis
  #   ports:
  #     - '6379:6379'
  #   volumes:
  #     - liquidation_bot_redis_data:/data

volumes:
  liquidation_bot_pg_data:
    driver: local
  # liquidation_bot_redis_data:
  #   driver: local
